# Generated by Django 2.2.16 on 2022-04-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220419_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='接口测试报告', max_length=80),
        ),
    ]
