# Generated by Django 2.2.16 on 2022-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_api_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractor',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='param',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='validator',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
