# Generated by Django 2.2.16 on 2022-03-25 06:31

import frames.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('description', frames.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('update_datetime', frames.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', frames.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('zh_name', models.CharField(default='', max_length=100)),
                ('sys', models.IntegerField(default=1)),
                ('point_type', models.IntegerField(default=1)),
                ('key_yn', models.IntegerField(default=1)),
                ('from_page', models.CharField(default='', max_length=100)),
                ('from_page_ext', models.TextField(default='')),
                ('curr_page', models.CharField(default='', max_length=100)),
                ('curr_page_ext', models.TextField(default='')),
                ('from_action', models.CharField(default='', max_length=100)),
                ('from_action_ext', models.TextField(default='')),
            ],
            options={
                'verbose_name': '标准埋点表',
                'verbose_name_plural': '标准埋点表',
            },
        ),
        migrations.CreateModel(
            name='PointExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('description', frames.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('update_datetime', frames.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', frames.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('ctime', models.IntegerField(default=0)),
                ('point_type', models.IntegerField(default=1)),
                ('from_page', models.CharField(default='', max_length=100)),
                ('from_page_ext', models.TextField(default='')),
                ('curr_page', models.CharField(default='', max_length=100)),
                ('curr_page_ext', models.TextField(default='')),
                ('from_action', models.CharField(default='', max_length=100)),
                ('from_action_ext', models.TextField(default='')),
                ('details', models.TextField(default='')),
            ],
            options={
                'verbose_name': '拦截埋点记录表',
                'verbose_name_plural': '拦截埋点记录表',
            },
        ),
    ]
