# Generated by Django 2.2.16 on 2022-04-21 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import frames.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', frames.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('modifier', frames.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', frames.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', frames.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('version', models.CharField(default='', max_length=50)),
                ('build_no', models.CharField(default='', max_length=50)),
                ('branch', models.CharField(default='', max_length=255)),
                ('filepath', models.CharField(default='', max_length=255)),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '发布记录表',
                'verbose_name_plural': '发布记录表',
                'ordering': ['-id'],
                'unique_together': {('version', 'build_no', 'status')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', frames.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('modifier', frames.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', frames.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', frames.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('module_name', models.CharField(default='', max_length=50)),
                ('module_size', models.IntegerField(default=0)),
                ('module_type', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='Module.creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('publish', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='performance.Publish')),
            ],
            options={
                'verbose_name': '模块大小表',
                'verbose_name_plural': '模块大小表',
                'ordering': ['-id'],
                'unique_together': {('publish', 'module_name')},
            },
        ),
    ]
