# Generated by Django 2.2.16 on 2022-04-19 03:02

from django.db import migrations, models
import frames.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packageAnalyse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('description', frames.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('update_datetime', frames.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', frames.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '基本模型',
                'verbose_name_plural': '基本模型',
                'abstract': False,
            },
        ),
    ]
