# Generated by Django 2.2.16 on 2022-04-15 09:49

from django.db import migrations, models
import frames.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsocketLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', frames.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', frames.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', frames.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', frames.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('group_name', models.CharField(help_text='分组名称', max_length=256, verbose_name='分组名称')),
                ('url', models.CharField(help_text='请求链接', max_length=256, verbose_name='连接url')),
                ('kwargs', models.TextField(help_text='运行参数', max_length=1024, verbose_name='执行参数')),
                ('status', models.BooleanField(default=True, verbose_name='运行状态')),
            ],
            options={
                'verbose_name': 'websocket日志',
                'verbose_name_plural': 'websocket日志',
            },
        ),
    ]
