# Generated by Django 2.2.16 on 2022-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20220415_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='sysfiles',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
