# Generated by Django 2.2.16 on 2022-04-18 03:16

from django.db import migrations, models
import django.db.models.deletion
import frames.fields


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', frames.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('update_datetime', frames.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', frames.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('moduleName', models.CharField(max_length=64, verbose_name='模块名称')),
                ('orderNum', models.IntegerField(verbose_name='显示排序')),
                ('owner', models.CharField(blank=True, max_length=32, null=True, verbose_name='负责人')),
                ('status', models.CharField(blank=True, max_length=8, null=True, verbose_name='模块状态')),
                ('dept', models.ForeignKey(db_constraint=False, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='moduleDept', to='permission.Dept', verbose_name='所属部门')),
                ('parentId', models.ForeignKey(blank=True, db_constraint=False, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='permission.Module', verbose_name='上级模块')),
            ],
            options={
                'verbose_name': '模块管理',
                'verbose_name_plural': '模块管理',
            },
        ),
    ]
