# Generated by Django 2.2.16 on 2022-04-13 13:49

import apps.permission.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=apps.permission.models.users.avatar_path, verbose_name='头像'),
        ),
    ]
