# Generated by Django 2.2.16 on 2022-04-18 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='dept',
        ),
    ]
