# Generated by Django 2.2.16 on 2022-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_remove_module_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
